name: supercell
version: "2.1.0"
license: GPL-2.0-only
issues: https://github.com/orex/supercell/issues
contact: kirill.okhotnikov@gmail.com
website: https://orex.github.io/
source-code: https://github.com/orex/supercell
summary: Disordered crystal structures transformation software.
description: |
  A a combinatorial structure-generation approach for the local-level 
  modeling of atomic substitutions and partial occupancies in crystals. 
  It uses supercell approximation and enumeration algorithm to convert 
  structures with vacancies and/or substitution to "binary" occupied.
  The program mostly uses to prepare DFT calculations of battery matrials,
  semiconductors etc.

base: core22
grade: stable
confinement: strict
type: app

architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: arm64
    build-for: arm64

parts:
  supercell:
    plugin: cmake
    cmake-parameters:
      - '-DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX='
    source-type: local
    source: .
    build-packages:
      - build-essential
      - cmake
      - libarchive-dev
      - libboost-program-options1.74-dev
      - libboost-filesystem1.74-dev
      - libboost-test1.74-dev
      - libboost-system1.74-dev
      - libtbb-dev
      - libeigen3-dev
      - liblzma-dev
      - libbz2-dev
      - zlib1g-dev
    stage-packages:
      - libarchive13
      - libtbb12
      - libboost-program-options1.74.0
      - libboost-filesystem1.74.0
      - libboost-system1.74.0
      - liblzma5
      - zlib1g

apps:
  supercell:
    command: bin/supercell
    plugs: [home, removable-media]
